name: CodeProject.AI Server (Raspberry Pi)
version: 2.1.9
url: https://github.com/codeproject/CodeProject.AI-Server
slug: codeproject-ai-rpi,
description: "CodeProject Server is a self contained service that software developers can include in, and distribute with, their applications in order to augment their apps with the power of AI."
arch: 
  - aarch64
startup: application
boot: auto
webui: http://[HOST]:[PORT:5000]
ports:
  5000/tcp: 7000
ports_description:
  5000/tcp: "[Optional] Port of your CodeProject.AI server"
environment:
  VISION-FACE: True
  VISION-DETECTION: True
  VISION-SCENE: True
  MODELSTORE-DETECTION: True
  TZ: ""
